### ISSUE TITLE
Add className to target's wrapper easy customization

### ISSUE THREAD

**Issue by orar** [littlebits/react-popover#190]
**Behaviour**: When popover shows, there is usually a span around the target element which encloses on the style of the target relative to its container.

Assuming i have a target
```css
.buttonContainer { 
  width: 200px; //doesnt matter
}

.blockButton {
  width: 100%;
  color: #fff
}
```

```jsx harmony
import Popover from 'react-popover';

const Button = () => {
  return <button className="blockButton">Block button</button>
}

<div className="buttonContainer">
  <Popover
    isOpen={false}
    body={<div>I'm a little teapot hanging on a button</div>} 
  >
    <Button />
  </Popover>
</div>
```
Initially (`isOpen=false`), Button will render full width of container (200px). Until popover wraps with a span decreasing the width of Button relative to container to length of Button text.

**Expectation**: If there should be a className attached to new span wrapper this could bear props of button without effect
